Bot:
  dummy_mode: true #A value of true indicates that orders will be 'dummy' (your balance will not be affected). A value of false indicates otherwise
  frequency: 5 #Minutes to wait between bot cycles
  min_initial_drop: 10 #Percentage (0-100) for the minimun drop for an order to consider
  min_additional_drop: 3 #Percentage (0-100) drop from previous orders to consider a new buy order in the same ticker
  tickers:
    - BTC
    - ETH
    - DOT
    - XMR
    - BCH
Binance:
  secret_key: XXXXX
  public_key: p5j3V7FHMEKDX96vydOJbgRz628rnFO3Fz1qFhVjRaMkY2V2ytGb1K6DWE8C7LOs
Telegram:
  bot_token: XXXX
  chat_id: XXX
