General:
  frequency: 5 # Minutes to wait between bot cycles
  order_amount_usd: 11 # Amount to trade in USD for each order
  min_initial_drop: 7 # Percentage (0-100) for the minimun drop for an order to consider
  min_additional_drop: 2 # Percentage (0-100) drop from previous orders to consider a new buy order in the same ticker
  retry_after: 15 # Minutes to wait for retrying after some inconvenience (e.g., insuficient funds
  dry_run: true # A value of true indicates that orders will be 'dummy' (your balance will not be affected). A value of false indicates otherwise
  tickers:
    - BTC
    - ETH
    - DOT
    - XMR
    - BCH
Exchange:
  exchange_name: Binance
  api_key: YOUR_API_KEY
  api_secret: YOUR_API_SECRET
IM:
  telegram_bot_token: YOUR_TELEGRAM_BOT
  telegram_chat_id: YOUR_TELEGRAM_CHAT_ID
